### PR TITLE
The weapon mods and weapons compatbility that I've promised

### PR DESCRIPTION
**Pull request by ElWrobel**
It's not finished yet and there's a lot of changes outside of the added mods, some are balance changes, some are bugfixes, good luck :D

### CODE REVIEW

**Comment by ElWrobel** [comment]
Oh and let me know if I did this right, I've never used github before

**Comment by HugoZink** [comment]
Woah, cool!

Looks like your editor changed _all_ the lines though, not just the parts that were actually changed. Makes it a little harder, but that's fine.

I'll have to run this through a diff tool first, and then I'll have to run it through the Develop branch as well. Thanks for your contribution! I'll take a look at it later today, I only just got out of bed.

**Comment by HugoZink** [comment]
I can't merge this as-is, for the following reasons:

* A lot of weapons had their damage either increased or explicitly specified for no real reason
* The pull request is kinda messy and basically overwrites the whole file
* The MP7 and P90 can now shoot through shields, but there is already an ammo type for the MP7 and P90 which does that (at the cost of ammo pickup and some damage of course). Same goes for the Five-Seven.

I appreciate all the custom weapon support you added though, and I'll make sure to add those to the mod.

**Comment by ElWrobel** [comment]
Yeah, like I told you on modworkshop, I made a lot of changes as I never liked the fact that 9mm is as powerful as a 5.56, that most modifcations are deep_clone nostats and many of the weapons were functionally the same. I sent you this so you wouldn't have to sift through all the mods yourself and fish out the strings. I agree it could've been made simpler, but before this I barely ever touched a lua file, especially as complicated as the ones present in Irenfist.

I reversed the piercing ability for P90, MP7 and FiveseveN as otherwise they were basically the same as the rest of their contemporaries, instead of AP kit they gained HP ammo swap, this change allows to underline their primary function, especially with Gyurza and Veresk gaining the piercing ability in exchange for massive stats reductions.   

Anyways, I hope it comes in handy.

**Pull request closed without merging**
